### ISSUE TITLE
Keyboard shortcut ctrl+n does not always work

### ISSUE THREAD

**Issue by jprykiel** [speedball2001/identitychooser-mx#19] opened 2021-01-12 09:51 UTC
Hello.
I know this is an issue you have already tried to solve, it is better now, but not always working. I am using last available version of Thunderbird 64 bits on Windows 10, and this shortcut works for a while and then stops working until I restart Thunderbird. When it doesn't work, it does not open a new message, it just does nothing at all.
Tell me if I can help more to solve this issue.
Cheers.

**Comment by jprykiel** [comment] 2021-01-12 12:35
Here is an update to my issue.
ctrl+n works each time you send a new message, until you read a message, apparently read or unread does not make a difference. After reading a message and closing it, the shortcut stops working until next Thunderbird restart.
Hope this helps.
Cheers

**Comment by speedball2001** [comment] 2021-01-13 23:21
Interesting. Do you read a message by opening it in a new window, in a new tab?

**Comment by jprykiel** [comment] 2021-01-13 23:53
Okay. New tab does not give me this issue, but new window and existing window does. Unfortunately, these 2 options are easier to use for blind users using screen readers. Hope you can do something.
Cheers,
JPR

**Comment by speedball2001** [comment] 2021-01-13 23:56
Do you have any other addons installed? I can't reproduce the issue on my side, unfortunately. 

Do you see any error messages in Thunderbird's error console?

**Comment by jprykiel** [comment] 2021-01-14 08:16
Hello.
No other add-ons installed, can you tell me where to find the error console, it seems to have changed in recent versions, I've looked in developer tools but can't see it there anymore.
What else can I say? I am under Windows 10, Hardware acceleration is disabled, and I am using unified view. But everything was working perfectly with version 1 of your add-on, and of course previous Thunderbird versions.
Cheers.

**Comment by speedball2001** [comment] 2021-01-14 08:55
You can open the error console by pressing CTRL+SHIFT+J. The next time you notice that CTRL+N stopped working, please check if you can find anything in there.

**Comment by jprykiel** [comment] 2021-01-14 09:08
Can you see anything useful in there ?

[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Successfully loaded OpenPGP library rnp.dll from C:\Program Files (x86)\Mozilla Thunderbird\rnp.dll RNPLib.jsm:49:13
public keys: 0, secret keys: 0 RNPLib.jsm:247:15
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Successfully loaded OTR library libotr-5.dll from C:\Program Files (x86)\Mozilla Thunderbird\libotr-5.dll OTRLib.jsm:43:13
IdentityChooser#run -- begin background.js:10:13
Option#setupDefaultOptions -- begin options.js:24:13
Option#setupDefaultOptions: locally stored options: 
Object { icEnableComposeMessage: true, icEnableReplyMessage: true, icEnableForwardMessage: true, identitiesExtendedProps: {…} }
options.js:27:13
Options#setupDefaultOptions: set extended properties options.js:42:13
Option#setupDefaultOptions -- end options.js:73:13
IdentityChooser#run: onIdentityChosen listener registered background.js:15:13
IdentityChooser#run: iterate over accounts and identities background.js:17:13
IcIdentities#getIdentities -- begin identities.js:7:13
IcIdentities#getIdentities -- end 
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
identities.js:27:13
IdentityChooser#run: found undefined, id2 background.js:22:15
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: reply, hdrReplyButton implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: reply, hdrReplyToSenderButton implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: replyAll, hdrReplyAllButton implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: forward, hdrForwardButton implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: compose, button-newmsg implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: reply, button-reply implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: replyAll, button-replyall implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
WebExtensions: IcButton2#constructor -- begin implementation.js:9
WebExtensions: IcButton2#constructor: forward, button-forward implementation.js:10
WebExtensions: IcButton2#constructor -- end implementation.js:22
IdentityChooser#run: add identity  


Cheers,

**Comment by jprykiel** [comment] 2021-01-15 09:19
Do you have what you need?
I am attaching a longer file below.
Cheers,
JPR
[identity chooser debug.txt](https://github.com/speedball2001/identitychooser-mx/files/5819530/identity.chooser.debug.txt)

**Comment by speedball2001** [comment] 2021-01-15 16:50
Can you describe how you use Thunderbird? In your debug log it opens 2 windows to which Identity Chooser gets attached. It might be the case that Identity Chooser removes itself from the windows and de-registers the shortcut key, but I'm not sure.

I still can't reproduce this on my machine. I wonder if I need to use Thunderbird in a certain way in order to cause this issue.

**Comment by jprykiel** [comment] 2021-01-15 19:51
Hi.
I have 6 accounts, some are POP3, and some are IMAP. In the view menu, I alternate between grouped and ungrouped, but this doesn't change anything to identity chooser's behaviour. Also in the view menu,  classic layout and unified view are checked. 
I am using a screenreader but turning it off does not change the issue.
Anything else you need to know?
Cheers,
JPR

**Comment by jprykiel** [comment] 2021-01-24 18:17
Hi @speedball2001 
Last Beta did not cure my shortcut issue, I know it was not supposed to, but tell me if I can do anything more to help you reproduce it on your system.
It is probably due to a TB update as well, as IC and TB's previous versions did not have this issue.
Still hoping you can find a solution.
Cheers,
JPR

**Comment by jprykiel** [comment] 2021-11-07 14:05
Hello again,
now with TB 91 and identity chooser's latest version. My issue is unchanged, and I'm desperately wanting to use this wonderful add-on. I wonder if you could give it a 2nd look.
To summarize, I am visually impaired and therefore use TB with unified folders which is more convenient, and open message in the existing window.
Please, if you have time, look in my previous error console attachment, and please tell me if anything new comes to your mind.
I would also be curious to know if anyone else encountered this issue.

All the best,
JPR

**Comment by speedball2001** [comment] 2023-08-05 23:47
This should be finally fixed with Identity Chooser 4.0.

**Closed by speedball2001** 2023-08-05 23:47 UTC
