### ISSUE TITLE
When replying to message in Thunderbird 91.2.1, cursor starts in address box

### ISSUE THREAD

**Issue by vdefilippo** [speedball2001/identitychooser-mx#39] opened 2021-11-01 20:56 UTC
Hi,

I use identity chooser in Thunderbird and love it. Thanks for writing it.

With the recent Thunderbird update to 91.2.1, when replying to a message, the cursor stays in the address pane instead of starting in the compose section. So, instead of hitting "reply", choosing an identity, and then being able to start typing the message right away, you have to click in the compose window. Otherwise, if you start typing, Thunderbird tried to add another address.

This is new behaviour. I confirmed by temporarily disabling the add-on and trying without it. The behaviour goes back to normal.

I also tried removing and re-installing the add-on. Didn't work...

Do you have any suggestions?

Thanks very much,
Vito DeFilippo

**Comment by speedball2001** [comment] 2021-11-01 22:11
Duplicate of #36

**Closed by speedball2001** 2021-11-01 22:11 UTC
Labels: duplicate
