### ISSUE TITLE
Replying with some hightlighted email content doesn't just quote that text.  

### ISSUE THREAD

**Issue by TheBlackRoom** [speedball2001/identitychooser-mx#42] opened 2021-12-09 19:02 UTC
When the extension is installed I can no longer highlight some part of the content of the original email to use as the only content for the reply. i.e. by highling something before pressing reply, TB normally uses just that highlighted text in the reply. With Identity Chooser activated the whole original email content is used for the reply.

Turning off the option "_Show List of Identities When Clicking on Reply button_" solves this but then again this also stops the ability to choose an identity.

**Comment by speedball2001** [comment] 2021-12-14 09:39
I can reproduce this in my development environment. Since Identity Chooser only invokes the editor using Thunderbird's maile xtension API and doesn't do anything by itself I suspect that this is a bug in Thunderbird itself. I have to create a small test case, though, to confirm this.

**Comment by speedball2001** [comment] 2022-09-11 09:41
This is a duplicate of #22

**Closed by speedball2001** 2022-09-11 09:41 UTC
Labels: duplicate
