### ISSUE TITLE
TB 115

### ISSUE THREAD

**Issue by wiltet** [speedball2001/identitychooser-mx#57] opened 2023-07-12 08:27 UTC
Hi,

thanks a lot for this helpfull addon which I am using since the first day.

Is there a plan to continue and update this addon for TB 115? Would be really great.

**Comment by speedball2001** [comment] 2023-07-12 08:58
Due to other commitments I didn't have any time yet to even research if it is still possible to support TB115. I plan to look into it but can't promise anything.

**Comment by wiltet** [comment] 2023-07-13 17:17
Would be nice if its not to much work to change this and you can make us happy again.
Somehow its a bit a poor situation aslong as the TB-team does not care about that sort of basic things and leave the work to others.
Well, you deside... and I was lucky whith this extension for a long time and mabe will be as well in future. If you dive in to it, I wish you great success.

**Comment by speedball2001** [comment] 2023-07-26 20:18
Could you please play with version [4.1 beta 1](https://github.com/speedball2001/identitychooser-mx/releases/tag/4.0beta1)?

For now only the big blue "+ New Message" button is working. This may or may not change later.

In fact, I'm in contact with Thunderbird's addon coordinator. As far as I understand it, they'd rather that the addon stops adding menus to every button that could open a compose window. I'll see what alternative solution we come up with.

**Comment by WithThisHerring** [comment] 2023-07-29 22:16
I just installed 4.1 beta 1.  It works somewhat!

When I first installed it, my emails all disappeared (or were invisible?) but a quick restart of TB fixed that.

Clicking the "+ New Message" button shows my list of addresses as it should, but if I then go to another folder, reply to an email, and try "+ New Message" button again, it shows my list of addresses repeated 5 times or possibly more (it's hard to tell with the scrolling).  However, TB 115 has been VERY glitchy for me overall, so I have no idea what to attribute to your wonderful extension and what is another TB issue.  Restarting TB shrinks the number of duplicates.  Possibly I'm getting a new set of duplicates every time I switch to another folder or hit reply on another email.

Also, the email list is in a different order every iteration.

Duplicates appear like this (not sure if this is the actual pattern, as I have maybe 8 addresses):
Address 1
Address 2
Address 3
Address 3
Address 1
Address 2
Address 3
Address 2
Address 1

So it's not just Address 1 a half-dozen times followed by Address 2.

Arch Linux
linux 6.4.6
Thunderbird 115.0.1

I would still call this much better than not having your extension at all.

**Comment by jmoupah** [comment] 2023-07-31 11:14
Hi,

thanks for this module that helps me every days :)

I tried the 4.1 beta1 and here are my feedbacks : 

**Test 1**
- install the xpi
- the list of all accounts appears when I click on the big blue "+ New Message"
- restart TB
- the list doesn't appear anymore despite the module is active on the modules list page
- uninstall the module

**Test 2**
- instal the xpi
- the list of all accounts appears when I click on the big blue "+ New Message"
- choose the accounts to hide form the options page
- all accounts still appear in the list
- uninstall the module

For the record, I didn't uninstall the previous version before my 1st test, maybe my mistake.

Windows 11 (21H2) / TB 115.0.1 (64bits)

**Comment by speedball2001** [comment] 2023-07-31 11:44
Last week I talked to Thunderbird's addon coordinator John. They prefer that addons become pure mail extensions that don't use any experiments. We came up with a solution that -- instead of manipulating Thunderbird's UI -- opens a popup window when the the composer starts. So no menu attached to "new message", "reply" etc. anymore instead you'll choose the identity right after the composer opens.

I developed a prototype for this. It's not very attractive right now but for me it works.

Could guys please try it out and let me know? It's attached to this message.

[identitychooser.zip](https://github.com/speedball2001/identitychooser-mx/files/12214593/identitychooser.zip)

Do not extract the file. You may have to rename it to identitychooser.xpi, though.

**Comment by jmoupah** [comment] 2023-07-31 12:35
Ok, thanks.

I tried it, the pop-up opens as intended.

I have 2 screens and the pop up opens on the screen with the main TB window while the composer windows can open on the other screen (depends where was the last one).
Is there a way to "attach" the pop-up to the composer window because, when you click the big blue button, you expect that the next action (in the pop-up in this case) is on the screen with the composer window (don't know if it's clear ^^)

**Comment by speedball2001** [comment] 2023-07-31 12:55
> Is there a way to "attach" the pop-up to the composer window because, when you click the big blue button, you expect that the next action (in the pop-up in this case) is on the screen with the composer window (don't know if it's clear ^^)

Could you try this one? 

[identitychooser.zip](https://github.com/speedball2001/identitychooser-mx/files/12215167/identitychooser.zip)

**Comment by jmoupah** [comment] 2023-07-31 13:05
It works, nice :)

The position of the pop-up is a bit approximative but it's on the composer window ! Anyway, since it can't be on the button anymore, I think it's the best we'll get.

Thanks

**Comment by speedball2001** [comment] 2023-07-31 19:52
> It works, nice :)
> 
> The position of the pop-up is a bit approximative but it's on the composer window ! Anyway, since it can't be on the button anymore, I think it's the best we'll get.
> 
> Thanks

I styled the identity window a bit and localized all new texts.

Please test this version and let me know what you think.

[identitychooser.zip](https://github.com/speedball2001/identitychooser-mx/files/12221608/identitychooser.zip)

**Comment by jmoupah** [comment] 2023-07-31 20:31
I found this design system that looks nice : https://design.thunderbird.net/fundamentals

That could give something like that : 
![Screenshot 2023-07-31 at 22-19-39 Fundamentals - Thunderbird Design System](https://github.com/speedball2001/identitychooser-mx/assets/18148022/f58a773a-eca5-4a2a-a863-20c83f5c1f3a)

What you think ?

**Comment by speedball2001** [comment] 2023-07-31 21:31
I'll keep it in mind. Thunderbird's UI is in a transitionally phase right now. Let's wait what the team comes up with.

**Comment by jmoupah** [comment] 2023-08-01 07:27
Right, let's wait.

**Comment by elhennig** [comment] 2023-08-01 09:03
I use two different IDs to switch between ASCII and HTML composer, something TB still is not able to do. The new ID chooser does to switch the edit mode when choosing the appropriate ID. Can this be changed to the behavior with TB 102?

**Comment by WithThisHerring** [comment] 2023-08-04 04:09
I just tried the .zip that you posted in https://github.com/speedball2001/identitychooser-mx/issues/57#issuecomment-1659040351

It seems to look and work great!  It even plays nicely with my dark color scheme.  THANK YOU!!!!  No duplicate email list, popup comes up in the right place, everything is great!

**Comment by speedball2001** [comment] 2023-08-04 13:01
I did more work on the extension. If everything goes right, this one should be version that will be released as Identity Chooser 4.

For that I need your guys' help: Could you please install the attached version and let me know if it works for you? 

If you install or update the extension you will now see a page which documents changes due to the change in technology. I'd really appreciate if you could proof read it and let me know if everything makes sense. English is -- as you probably all know -- not my native language.

Thank you in advance for your help.

[identitychooser.zip 4.0beta6](https://github.com/speedball2001/identitychooser-mx/files/12260961/identitychooser.zip)

**Comment by WithThisHerring** [comment] 2023-08-05 04:41
The new attached version works!  It looks like it also will close bug https://github.com/speedball2001/identitychooser-mx/issues/54

The font size on email buttons and cancel button seems a bit small.  Maybe make it the same size as the line "Please select an identity to proceed"?

I really don't have that many changes to the English on the message that appears!  I don't know how to suggest changes properly in Github, so here they are:

Add comma (,) after last word in these phrases:
```
through a lot of changes over the years
buttons remain unchanged

```
Remove comma (,) in these phrases:
```
term support for both, Thunderbird and addons.
This means, Identity Chooser doesn't only work in the main

```
Change:
`longterm` -> change to `long-term`
`Identity Chooser in actions` -> change to `Identity Chooser in action`
`theses` -> change to `these`
`addons` -> change to `add-ons` (just so it matches that choice elsewhere :)  )

***************************************************
FYI weird English thing:
"These" is already the plural of "this".  "These" is one syllable that rhymes with "cheese."
"Theses" is actually a word, but it is the plural of "thesis."  "Theses" is two syllables and rhymes with "feces."  :P

**Comment by jmoupah** [comment] 2023-08-05 07:23
Thank you for this version that work's fine for me :)

My only feedback concerns the colors of the buttons : for better integration in the TB interface, maybe account buttons could be in blue as they are main buttons and cancel button turn to grey as it is secondary.

As you can see in the screenshot, main button is blue and others are gey :
![normal](https://github.com/speedball2001/identitychooser-mx/assets/18148022/205f02e6-91c5-4dfd-a8e0-a3cb22ba5773)

And hovering the main button, blue gets darker :
![over](https://github.com/speedball2001/identitychooser-mx/assets/18148022/04aecf34-653a-46f5-b8c2-a06dc3564f69)

**Comment by speedball2001** [comment] 2023-08-05 15:04
> Thank you for this version that work's fine for me :)
> 
> My only feedback concerns the colors of the buttons : for better integration in the TB interface, maybe account buttons could be in blue as they are main buttons and cancel button turn to grey as it is secondary.
> 
> As you can see in the screenshot, main button is blue and others are gey : ![normal](https://user-images.githubusercontent.com/18148022/258569756-205f02e6-91c5-4dfd-a8e0-a3cb22ba5773.png)
> 
> And hovering the main button, blue gets darker : ![over](https://user-images.githubusercontent.com/18148022/258569763-04aecf34-653a-46f5-b8c2-a06dc3564f69.png)

I tried it. To be honest, I find the stack of blue buttons a bit aggressive:
![2023-08-05 15_03_07-Identity Chooser - Mozilla Thunderbird](https://github.com/speedball2001/identitychooser-mx/assets/2027437/5df0a9eb-c971-46cd-ac0a-b9e0e3e570a7)

think that the blue color is supposed to highlight one important part of a screen.

Here's an alternative, but highlighting the cancel button may seem weird: 
![2023-08-05 17_01_22-Identity Chooser - Mozilla Thunderbird](https://github.com/speedball2001/identitychooser-mx/assets/2027437/5e102359-f3c3-418a-b493-d04e9865ee34)

I should probably ask on the developer chat if they have any suggestions for a color scheme.

What do you think?

I could also keep everything as it is and release it as Identity Chooser 4. Getting it out before Mozilla starts upgrading users automatically is important to me.

**Comment by speedball2001** [comment] 2023-08-05 15:07
> The new attached version works! It looks like it also will close bug #54

Good catch!
 
> The font size on email buttons and cancel button seems a bit small. Maybe make it the same size as the line "Please select an identity to proceed"?

Well, for others it's already too large for their list of emails. I may have to implement a setting where users can choose between various sizes. But that has to wait.
> 
> I really don't have that many changes to the English on the message that appears! I don't know how to suggest changes properly in Github, so here they are: [...]

Thank you, I've changed them on my side.

**Comment by MoralCode** [comment] 2023-08-05 23:53
my distro doesnt have TB115 yet, but I cant wait to use this update, the screenshots look awesome!

> The new attached version works! It looks like it also will close bug #54

closes #54  (sorry just putting the reference in the right format for the github overlords so that that issue should auto close when this gets merged)

**Comment by speedball2001** [comment] 2023-08-05 23:53
I released Identity Chooser 4.0 to addons.mozilla.org.

Thank you for helping with your comments and bug reports. 

If you find any bugs in this version, please open new bug reports.

**Closed by speedball2001** 2023-08-05 23:53 UTC

**Comment by WithThisHerring** [comment] 2023-08-06 16:23
I just went to https://addons.thunderbird.net/en-US/thunderbird/addon/identity-chooser/ and the new version is not there yet.  But, that page has the new screenshots.  Did something go wrong in putting up the new version, or does it take a while for the new version to get to the addons page?

**Comment by speedball2001** [comment] 2023-08-06 16:36
It's still in the review queue. I'm sure it will get approved soon.
