### ISSUE TITLE
Identity Chooser does not enhance main tool bar buttons for replying and forwarding

### ISSUE THREAD

**Issue by jimandro** [speedball2001/identitychooser-mx#12] opened 2020-11-10 12:42 UTC
First of all I would like to thank you for this very useful add on. I am using 78.4.2 with only two more add ons, Automatic Dictionary & Disable DragAndDrop. The only button that works and forces me to choose a sender is the compose button, the other three buttons, reply, replyb to all and forward do not have this add on activated. Can you please help me ?

Thanks in advance, Dimitrios

**Comment by speedball2001** [comment] 2020-11-10 17:15
Did you double check that the menu is enabled for reply and forward in Identity Chooser's settings?

**Comment by ziomau10** [comment] 2020-11-11 12:24
I joint Jimandro to thank you very much. I have dozens of accounts and this addon is a must for me.
As Jimandro I do not have the identity selector on Reply, reply to all anf forward buttons.
Unfortunately I do not see any "Identity chooser" option in tools menu ...
![Clipboard-1](https://user-images.githubusercontent.com/1978719/98811499-3e240200-2421-11eb-9ae7-eeb2c3d83d06.jpg)
Can you help me?

**Comment by speedball2001** [comment] 2020-11-11 12:32
The default place for settings is Addon Manager -> Identity Chooser -> "..." -> Settings. Please check this screen shot (it is in German, though):
![2020-11-11 13_29_37-Add-ons-Verwaltung - Mozilla Thunderbird](https://user-images.githubusercontent.com/2027437/98812220-619b7c80-2422-11eb-8ed9-63b716161de5.png)

**Comment by ziomau10** [comment] 2020-11-11 12:38
Thank you I found the options and everything is checked, and I restarted TB few times.
Any other idea?

Incredibly thunderbird 78 instead of standarizing a way to the options seems to alloy many (more) choices.
I have addon options all over the menus and in other places ... not easy to find them all ... sorry.

**Comment by speedball2001** [comment] 2020-11-11 12:44
Could you please deactive all other addons and try if that changes anything? I'm kinda sure that there are a couple of addons that simply don't play well with each other. I just don't know which.

**Comment by jimandro** [comment] 2020-11-11 12:47
I will try your suggestion and let you know, thank you

Στις Τετ, 11 Νοε 2020, 2:44 μ.μ. ο χρήστης speedball2001 <
notifications@github.com> έγραψε:

**Comment by ziomau10** [comment] 2020-11-11 12:50
Ok I just disabled everything else, restarted and still no chooser on other buttons.
WIndows 10 Pro Ver 1909
TB 78.4.2 (64-bit)

**Comment by jimandro** [comment] 2020-11-11 12:53
Same version of Windows and TB, I did the same thing, didn't work...

Στις Τετ, 11 Νοε 2020, 2:50 μ.μ. ο χρήστης Maurizio Ferraris <
notifications@github.com> έγραψε:

**Comment by speedball2001** [comment] 2020-11-11 12:58
What happens when you disable and enable Identity Chooser in the addon manager (without restarting TB)?

Also: We do talk about the replay and forward buttons in the message header, right?
![2020-11-11 13_57_21-Posteingang - janek@janek org - Mozilla Thunderbird](https://user-images.githubusercontent.com/2027437/98814448-f9e73080-2425-11eb-816a-e08099750699.png)

**Comment by speedball2001** [comment] 2020-11-11 13:00
Another comment: Could you please install the latest beta version and test with that: https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1-beta

**Comment by jimandro** [comment] 2020-11-11 13:00
I'm sorry, I just left my office, I will get back to you tomorrow morning
with an answer

Στις Τετ, 11 Νοε 2020, 2:58 μ.μ. ο χρήστης speedball2001 <
notifications@github.com> έγραψε:

**Comment by jimandro** [comment] 2020-11-11 13:02
Ok, I will and let you know...

Thank you again

Στις Τετ, 11 Νοε 2020, 3:00 μ.μ. ο χρήστης speedball2001 <
notifications@github.com> έγραψε:

**Comment by ziomau10** [comment] 2020-11-11 13:22
To me the problem is on the main toolbar:
![image](https://user-images.githubusercontent.com/1978719/98816349-d4a7f180-2428-11eb-875b-2ca520f2a889.png)
I tied the following as per your seggestion:
- Disabled every other extension
- Restarted TB
- Disbale Identity Chooser
- Restarted TB
- Enabled IC
- Restarted TB
- Enabled everything else
In any of these staps the IC arrow appeared next to the Reply, Reply All, or Forward buttons.
The arrow next to Forward allows only to select inline or attachment as default

**Comment by speedball2001** [comment] 2020-11-11 16:30
> To me the problem is on the main toolbar:

That's the issue: Identity Chooser modifies only the reply and forward buttons in the message header.

**Comment by ziomau10** [comment] 2020-11-11 18:26
I see... and of course it works as described ...
but ... is there a technical reason for that? ... a limit of TB78?
I remember that in TB68 also the main toolbar buttons were modified.
Sorry to ask, but I am not so confortable to use the single mail buttons but I am used to click on the main toolbar ... ;)
Anyway, if it is possible I request it as an improvement or "feature request" ...
Otherwise I will try to get used to mail toolbar instead.
Thank you for the great work!!

**Comment by speedball2001** [comment] 2020-11-12 11:40
The old version of Identity Chooser enhanced everything I could find in Thunderbird that could open an email editor (for instance mailto links in emails). As I set out to re-implement Identity Chooser as a mail extension with as little non-mailextension experiments as possible I decided to only implement what I use myself and see what happens.

Identity Chooser 2 basically is a minimum viable product. 

I intend to keep the feature set small because I don't know what the feature of Thunderbird extensions will be. I assume, though, that enhancing the other main toolbar buttons should be easy and I'll look into it, but I'm not making any promises.

**Comment by ziomau10** [comment] 2020-11-12 12:02
Absolutely acceptable...
Great job!
Thank you.

**Comment by speedball2001** [comment] 2020-12-04 16:46
I implemented Identity Chooser for the main toolbar buttons.

Please install version 2.1beta3 from https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1beta3 and let me know if it works as expected.

**Comment by jimandro** [comment] 2020-12-07 07:28
Good morning, it worked, thank you so much!!!!!!!!!

Στις 4/12/2020 6:47 μ.μ., ο/η speedball2001 έγραψε:

**Comment by speedball2001** [comment] 2020-12-10 15:19
I just released version 2.1beta4. Please confim that the issue is fixed now.

See: https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1beta4

**Comment by speedball2001** [comment] 2020-12-15 13:27
I released Identity Chooser 2.1 and submitted the new version to addons.thunderbird.net. Version 2.1 fixes this bug.

**Closed by speedball2001** 2020-12-15 13:27 UTC
